{% set ucx_version = "1.15.0" %}
{% set number = "1" %}


package:
  name: ucx-split

source:
  url: https://github.com/openucx/ucx/archive/v{{ ucx_version }}.tar.gz
  sha256: e3082101dd61b2482390e7917b390f0fe9ecf399a839d97ee025ee559e6cb12d

build:
  skip: true  # [not linux or cuda_compiler_version in ("None", "11.2")]
  number: {{ number }}

outputs:
  - name: ucx
    version: {{ ucx_version }}
    build:
      number: {{ number }}
      run_exports:
        - {{ pin_subpackage("ucx", max_pin="x.x") }}
      ignore_run_exports:
        - rdma-core
      ignore_run_exports_from:
        - {{ compiler("cuda") }}
    requirements:
      build:
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - {{ compiler("cuda") }}
        - {{ cdt("libnl") }}             # [cdt_name == "cos6"]
        - {{ cdt("libnl3") }}            # [cdt_name == "cos7"]
        - automake
        - autoconf
        - libtool
        - make
        - pkg-config
      host:
        - cuda-cudart-dev ={{ cuda_compiler_version }}     # [(cuda_compiler_version or "None").startswith("12")]
        - cuda-nvml-dev ={{ cuda_compiler_version }}       # [(cuda_compiler_version or "None").startswith("12")]
        - libnuma
        - rdma-core  # [linux64]
      run:
        - rdma-core >={{ rdma_core }}  # [linux64]
      run_constrained:
        - cuda-version >=11.2,<12  # [(cuda_compiler_version or "None").startswith("11")]
        - cuda-version >=12,<13    # [(cuda_compiler_version or "None").startswith("12")]

    script: install_ucx.sh
    test:
      commands:
        - test -f "${PREFIX}/bin/ucx_info"
        # Requires driver for GPU test.
        # Crashes qemu on ppc64le.
        - ${PREFIX}/bin/ucx_info -v         # [cuda_compiler_version == "None" and not ppc64le]
    about:
      home: https://openucx.org
      license: BSD-3-Clause
      license_family: BSD
      license_file: LICENSE
      summary: Unified Communication X.
      dev_url: https://github.com/openucx/ucx
      doc_url: https://openucx.readthedocs.io/

about:
  home: https://github.com/openucx/ucx
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Unified Communication X.
  dev_url: https://github.com/openucx/ucx
  doc_url: https://openucx.readthedocs.io/

extra:
  recipe-maintainers:
    - Akshay-Venkatesh
    - jakirkham
    - quasiben
    - TomAugspurger
    - leofang
    - matthiasdiener
